version: "3.9"

services:
  bot-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: bash
